version: "3.8"

services:
  api-gateway:
    build: ./ # build from Dockerfile in this folder
    container_name: api-gateway
    environment:
      AUTH_SERVICE_URL: http://auth-service:4005
    ports:
      - "4004:4004"
    networks:
      - app-network

networks:
  app-network:
    external: true
