version: "3.8"

services:
  auth-service:
    build: ./   # build from Dockerfile in this folder
    container_name: auth-service
    environment:
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      JWT_SECRET: V3l2R1hKMGZTRWR5T1JsaFZ5b21vNEdjZ0Z2ajdwQ0k=
    networks:
      - app-network

networks:
  app-network:
    external: true
