version: "3.8"

services:
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5400:5432"
    volumes:
      - /Users/hasangaranasinghe/Documents/db-volume/patient-service-db:/var/lib/postgresql
    networks:
      - app-network

  patient-service:
    build: ./   # build from Dockerfile in this folder
    container_name: patient-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
    depends_on:
      - patient-service-db
    networks:
      - app-network

networks:
  app-network:
    external: true
